# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20170810_0931'),
        ('owners', '0002_auto_20170807_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderOwnerRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Order')),
            ],
            options={
                'verbose_name': 'owner right',
                'verbose_name_plural': 'owner rights',
            },
        ),
        migrations.CreateModel(
            name='RightType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'right type',
                'verbose_name_plural': 'right types',
            },
        ),
        migrations.AlterModelOptions(
            name='ownerdatabase',
            options={'verbose_name': 'owner', 'verbose_name_plural': 'owners'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'owner question', 'verbose_name_plural': 'owner questions'},
        ),
        migrations.AddField(
            model_name='orderownerright',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='owners.OwnerDatabase'),
        ),
        migrations.AddField(
            model_name='orderownerright',
            name='right_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='owners.RightType'),
        ),
    ]
