# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_auto_20170810_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='seen_by_user',
        ),
    ]
