# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0004_remove_question_seen_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerdatabase',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownerdatabase',
            name='contact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ownerdatabase',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ownerdatabase',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
