# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import owners.models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0005_auto_20171029_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerdatabase',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=owners.models.image_path),
        ),
    ]
