# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0007_auto_20171029_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderownerright',
            name='price',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
