# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import owners.models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0013_auto_20171101_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderownerright',
            name='owner_pdf',
            field=models.FileField(blank=True, null=True, upload_to=owners.models.owner_pdf_path),
        ),
    ]
