# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20170824_0921'),
        ('accounts', '0005_resetpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('offer', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_offer_order', to='orders.Order')),
            ],
        ),
    ]
