# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0007_auto_20171029_1451'),
        ('accounts', '0007_userquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='counteroffer',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner_counter', to='owners.OwnerDatabase'),
            preserve_default=False,
        ),
    ]
