# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_counteroffer_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counteroffer',
            name='offer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='counteroffer',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
