# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20171029_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counteroffer',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_counter', to='owners.OrderOwnerRight'),
        ),
    ]
