# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='preview_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
