# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfilmmaking',
            name='film_length',
            field=models.BooleanField(choices=[(0, 'short film'), (1, 'full length')]),
        ),
        migrations.AlterField(
            model_name='orderfilmmaking',
            name='film_programming',
            field=models.BooleanField(choices=[(0, 'no'), (1, 'yes')]),
        ),
        migrations.AlterField(
            model_name='orderfilmmaking',
            name='film_trailer',
            field=models.BooleanField(choices=[(0, 'no'), (1, 'yes')]),
        ),
    ]
