# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170802_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderadvertisingdetail',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderadvertisingdetail',
            name='is_non_profit',
            field=models.CharField(choices=[('no', 'no'), ('yes', 'yes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='orderindieprojectdetail',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderindieprojectdetail',
            name='is_non_profit',
            field=models.CharField(choices=[('no', 'no'), ('yes', 'yes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='orderprogrammingdetail',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderprogrammingdetail',
            name='is_non_profit',
            field=models.CharField(choices=[('no', 'no'), ('yes', 'yes')], max_length=3),
        ),
    ]
