# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170730_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderadvertising',
            name='distribution',
            field=models.ManyToManyField(related_name='order_dist_advertising', to='orders.OrderDistributionProgramming'),
        ),
        migrations.AlterField(
            model_name='orderfilmmaking',
            name='distribution',
            field=models.ManyToManyField(related_name='order_dist_indie', to='orders.OrderDistributionIndie'),
        ),
        migrations.AlterField(
            model_name='orderprogramming',
            name='distribution',
            field=models.ManyToManyField(related_name='order_dist_programming', to='orders.OrderDistributionProgramming'),
        ),
    ]
