# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20170805_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderadvertisingdetail',
            options={'verbose_name': 'advertising project details', 'verbose_name_plural': 'advertising projects details'},
        ),
        migrations.AlterModelOptions(
            name='orderdistributionindie',
            options={'verbose_name': 'indie film distribution option', 'verbose_name_plural': 'indie film distribution options'},
        ),
        migrations.AlterModelOptions(
            name='orderdistributionprogramming',
            options={'verbose_name': 'programming distribution option', 'verbose_name_plural': 'programming distribution options'},
        ),
        migrations.AlterModelOptions(
            name='orderindieprojectdetail',
            options={'verbose_name': 'film making project details', 'verbose_name_plural': 'film making projects details'},
        ),
        migrations.AlterModelOptions(
            name='orderwedding',
            options={'verbose_name': 'wedding project', 'verbose_name_plural': 'wedding projects'},
        ),
        migrations.AddField(
            model_name='orderdistributionindie',
            name='explanation',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdistributionprogramming',
            name='explanation',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
