# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20170805_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttype',
            name='explanation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
