# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_projecttype_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('sent', 'Sent'), ('attention', 'Attention'), ('payment', 'payment'), ('done', 'Done')], default='sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderadvertisingdetail',
            name='budget',
            field=models.CharField(choices=[('low', '$0-50k Budget'), ('med', '$50-250k Budget'), ('high', '$250-500k Budget'), ('very', '$500k+ Budget')], default='low', max_length=5),
        ),
        migrations.AlterField(
            model_name='orderindieprojectdetail',
            name='budget',
            field=models.CharField(choices=[('low', '$0-50k Budget'), ('med', '$50-250k Budget'), ('high', '$250-500k Budget'), ('very', '$500k+ Budget')], default='low', max_length=5),
        ),
        migrations.AlterField(
            model_name='orderprogrammingdetail',
            name='budget',
            field=models.CharField(choices=[('low', '$0-50k Budget'), ('med', '$50-250k Budget'), ('high', '$250-500k Budget'), ('very', '$500k+ Budget')], default='low', max_length=5),
        ),
    ]
