# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20170809_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderadvertisingdetail',
            name='is_non_profit',
            field=models.CharField(choices=[('no', 'non profit'), ('yes', 'profit')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='orderindieprojectdetail',
            name='is_non_profit',
            field=models.CharField(choices=[('no', 'non profit'), ('yes', 'profit')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='orderprogrammingdetail',
            name='is_non_profit',
            field=models.CharField(choices=[('no', 'non profit'), ('yes', 'profit')], default='no', max_length=3),
        ),
    ]
