# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20170810_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rate', models.SmallIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_rate_us', to='orders.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='orderadvertisingdetail',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='orderindieprojectdetail',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='orderprogrammingdetail',
            name='rate',
        ),
    ]
