# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20170810_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='license_pdf',
            field=models.FileField(default='hello', upload_to=orders.models.license_path),
            preserve_default=False,
        ),
    ]
