# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_supporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateus',
            name='rate',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
