# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20171015_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='clearance',
            field=models.FileField(blank=True, null=True, upload_to=orders.models.clearance_path),
        ),
    ]
