# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_order_clearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaldistribution',
            name='ext_other',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='webdistribution',
            name='web_other',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderadvertisingdetail',
            name='is_non_profit',
            field=models.CharField(choices=[('no', 'non profit'), ('yes', 'profit')], default='yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='orderindieprojectdetail',
            name='is_non_profit',
            field=models.CharField(choices=[('no', 'non profit'), ('yes', 'profit')], default='yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='orderprogrammingdetail',
            name='is_non_profit',
            field=models.CharField(choices=[('no', 'non profit'), ('yes', 'profit')], default='yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='orderwedding',
            name='num_uses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
